name: build repo

on:
  push:
    branches: [ master ]

jobs:
  builds:
    name: build repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build repo
        run: |
          echo "$GPG_KEY" > ./key.asc
          ./repogen-linux-64bit --generate-web --generate-contents ./key.asc ./packages ./out
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
